import BinarySearchTreeNode from '../BinarySearchTreeNode'

describe("测试 binarySearchTreeNode", () => {
  it("测试insert", () => {
    const root = new BinarySearchTreeNode()
    root.insert(0)
    expect(root.value).toBe(0)
    root.insert(1)
    expect(root.right.value).toBe(1)
    root.insert(-1)
    expect(root.left.value).toBe(-1)
    root.insert(0.5)
    expect(root.right.left.value).toBe(0.5)
  })

  it("测试find", () => {
    const root = new BinarySearchTreeNode()
    root.insert(0)
    root.insert(1)
    root.insert(-1)
    root.insert(0.5)
    root.find(0)
    expect(root.find(2)).toBeNull()
  })

  it("测试findMin", () => {
    const root = new BinarySearchTreeNode()
    root.insert(0)
    expect(root.findMin().value).toBe(0)
    root.insert(1)
    root.insert(-1)
    root.insert(0.5)
    root.find(0)
    expect(root.findMin().value).toBe(-1)
  })

  it("测试contains", () => {
    const root = new BinarySearchTreeNode()
    root.insert(0)
    root.insert(1)
    root.insert(-1)
    root.insert(0.5)
    expect(root.contains(0)).toBe(true)
    expect(root.contains(1)).toBe(true)
    expect(root.contains(0.5)).toBe(true)
    expect(root.contains(-1)).toBe(true)
    expect(root.contains(2)).toBe(false)
  })

  it("测试toString", () => {
    const root = new BinarySearchTreeNode()
    expect(root.toString()).toBe("")
    root.insert(0)
    root.insert(1)
    root.insert(-1)
    root.insert(0.5)
    expect(root.toString()).toBe("-1,0,0.5,1")
  })

  it("测试remove", () => {
    const root = new BinarySearchTreeNode()
    root.insert(0)
    root.insert(1)
    root.insert(-1)
    root.insert(0.5)
    root.insert(2)
    expect(root.toString()).toBe("-1,0,0.5,1,2")
    root.remove(1)
    expect(root.toString()).toBe("-1,0,0.5,2")
    root.remove(0)
    expect(root.toString()).toBe("-1,0.5,2")
    root.remove(-1)
    expect(root.toString()).toBe("0.5,2")
    root.remove(2)
    expect(root.toString()).toBe("0.5")
    root.remove(0.5)
    expect(root.toString()).toBe("")
  })
})
