import DoubleLinkedList from '../doubleLinkedList'

describe("test doubleLinkedList", () => {
  it("test init list", () => {
    let list = new DoubleLinkedList()
    expect(list.head).toBeNull()
    expect(list.head).toBeNull()
  })

  it("test prepend", () => {
    let list = new DoubleLinkedList()
    list.prepend("second")
    expect(list.head.value).toBe("second")
    expect(list.tail.value).toBe("second")
    expect(list.tail).toEqual(list.head)
    expect(list.head.prev).toBeNull()
    expect(list.tail.next).toBeNull()
    list.prepend("first")
    expect(list.head.value).toBe("first")
    expect(list.tail.value).toBe("second")
    expect(list.head.next).toEqual(list.tail)
    expect(list.tail.prev).toEqual(list.head)
    expect(list.head.prev).toBeNull()
    expect(list.tail.next).toBeNull()
  })

  it("test append", () => {
    let list = new DoubleLinkedList()
    list.append("first")
    expect(list.head.value).toBe("first")
    expect(list.tail.value).toBe("first")
    expect(list.tail).toEqual(list.head)
    expect(list.head.prev).toBeNull()
    expect(list.tail.next).toBeNull()
    list.append("second")
    expect(list.head.value).toBe("first")
    expect(list.tail.value).toBe("second")
    expect(list.head.next).toEqual(list.tail)
    expect(list.tail.prev).toEqual(list.head)
    expect(list.head.prev).toBeNull()
    expect(list.tail.next).toBeNull()
  })

  it("test delHead", () => {
    let list = new DoubleLinkedList()
    let firstNode = list.append("first").append("second").delHead()
    expect(firstNode.value).toBe("first")
    expect(firstNode.next).toBeNull()
    expect(firstNode.prev).toBeNull()
    expect(list.head.prev).toBeNull()
    expect(list.head).toEqual(list.tail)
    let secondNode = list.delHead()
    expect(secondNode.value).toBe("second")
    expect(secondNode.next).toBeNull()
    expect(secondNode.prev).toBeNull()
    expect(list.head).toBeNull()
    expect(list.tail).toBeNull()
  })

  it("test delTail", () => {
    let list = new DoubleLinkedList()
    let firstNode = list.append("first").append("second").delTail()
    expect(firstNode.value).toBe("second")
    expect(firstNode.next).toBeNull()
    expect(firstNode.prev).toBeNull()
    expect(list.tail.next).toBeNull()
    expect(list.head).toEqual(list.tail)
    let secondNode = list.delTail()
    expect(secondNode.value).toBe("first")
    expect(secondNode.next).toBeNull()
    expect(secondNode.prev).toBeNull()
    expect(list.head).toBeNull()
    expect(list.tail).toBeNull()
  })
})
